import styles from "../styles/Home.module.css";
import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Link from "next/link";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Cuvette Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar/>
      <main className="main">
        <h1 className={styles.head}>Hi Company user, Welcome to Cuvette Tech.</h1>
        <Link href="/PostJobPg1">
        <div className={styles.PostJobBtn}>
          + Post a Job
        </div>
        </Link>
      </main>
    </div>
  );
}
